import bcrypt from "bcryptjs";
import { prisma, PrismaUserRepository, PrismaCredentialRepository } from "@trading/database";
import type { DecisionEventType, Portfolio, User } from "@trading/domain";
import { PrismaPortfolioRepository } from "@trading/database";

const userRepository = new PrismaUserRepository();
const credentialRepository = new PrismaCredentialRepository();
const portfolioRepository = new PrismaPortfolioRepository();

const TEST_PASSWORD = "correct-horse-battery-staple";

export interface TestUser {
  user: User;
  password: string;
}

/**
 * Creates a user with a real, login-able credential directly through
 * the repositories — there is no registration endpoint yet (deferred
 * to Phase 4, RBAC), so integration tests seed identity this way
 * instead of going through HTTP.
 *
 * Each call uses a random email so tests can run concurrently without
 * unique-constraint collisions, matching the pattern already used by
 * the repository test suites (e.g. prisma-asset-repository.test.ts).
 */
export async function createTestUser(): Promise<TestUser> {
  const user = await userRepository.create({
    email: `test-${crypto.randomUUID()}@example.com`,
    displayName: "Integration Test User",
  });

  const passwordHash = await bcrypt.hash(TEST_PASSWORD, 10);
  await credentialRepository.create({ userId: user.id, passwordHash });

  return { user, password: TEST_PASSWORD };
}

/** Creates a portfolio owned by the given user, with sensible defaults. */
export async function createTestPortfolio(
  userId: string,
  overrides: { name?: string; baseCurrency?: string } = {},
): Promise<Portfolio> {
  return portfolioRepository.create({
    userId,
    name: overrides.name ?? "Integration Test Portfolio",
    baseCurrency: overrides.baseCurrency ?? "USD",
  });
}

export interface TestAssetHandle {
  id: string;
}

/** Creates a disposable asset with a unique symbol, for transaction tests. */
export async function createTestAsset(symbolPrefix = "TST"): Promise<TestAssetHandle> {
  const asset = await prisma.asset.create({
    data: {
      symbol: `${symbolPrefix}-${crypto.randomUUID().slice(0, 8)}`,
      name: "Integration Test Asset",
      assetType: "STOCK",
      currency: "USD",
      exchange: "MOCK",
    },
  });
  return { id: asset.id };
}

/**
 * Creates a notification for the given user directly through Prisma —
 * there is no public endpoint to create notifications (they are
 * generated by system events, not by API callers), so tests seed them
 * here. Pass `read: true` to create it already marked as read.
 */
export async function createTestNotification(
  userId: string,
  overrides: { title?: string; read?: boolean } = {},
): Promise<{ id: string }> {
  const row = await prisma.notification.create({
    data: {
      userId,
      type: "test.integration",
      title: overrides.title ?? "Integration test notification",
      message: "Created by an integration test.",
      severity: "INFO",
      ...(overrides.read === true ? { readAt: new Date() } : {}),
    },
  });
  return { id: row.id };
}

export interface TestDecisionEventInput {
  type: DecisionEventType;
  timestamp: Date;
  payload?: Record<string, string | number>;
}

/**
 * Creates a decision (with entry/target/stop prices in USD) and its
 * events directly through Prisma — there is no write endpoint for
 * decisions yet. Events are inserted in the order given, so tests can
 * pass them out of chronological order to verify the API sorts them.
 * Cascade deletes (Portfolio -> Decision -> DecisionEvent) mean
 * `cleanupTestData` needs no extra step for these rows.
 */
export async function createTestDecision(
  portfolioId: string,
  assetId: string,
  overrides: {
    title?: string;
    direction?: "LONG" | "SHORT" | "NEUTRAL";
    createdAt?: Date;
    events?: TestDecisionEventInput[];
  } = {},
): Promise<{ id: string }> {
  const decision = await prisma.decision.create({
    data: {
      portfolioId,
      assetId,
      title: overrides.title ?? "Integration test decision",
      thesis: "Created by an integration test.",
      direction: overrides.direction ?? "LONG",
      entryPrice: 150,
      targetPrice: 170,
      stopPrice: 140,
      currency: "USD",
      riskLevel: "MODERATE",
      createdAt: overrides.createdAt ?? new Date("2026-06-01T14:00:00Z"),
    },
  });

  for (const event of overrides.events ?? []) {
    await prisma.decisionEvent.create({
      data: {
        decisionId: decision.id,
        type: event.type,
        timestamp: event.timestamp,
        payload: event.payload ?? {},
      },
    });
  }

  return { id: decision.id };
}

/**
 * Creates a position directly through Prisma (USD). Positions are
 * normally a projection of transaction history, but scenario tests need
 * a known, fixed baseline without going through transaction creation.
 */
export async function createTestPosition(
  portfolioId: string,
  assetId: string,
  overrides: { quantity?: number; averageEntryPrice?: number; currentPrice?: number } = {},
): Promise<{ id: string }> {
  const row = await prisma.position.create({
    data: {
      portfolioId,
      assetId,
      quantity: overrides.quantity ?? 10,
      currency: "USD",
      averageEntryPrice: overrides.averageEntryPrice ?? 100,
      currentPrice: overrides.currentPrice ?? 100,
      openedAt: new Date("2026-01-01T00:00:00Z"),
    },
  });
  return { id: row.id };
}

/**
 * Creates a scenario directly through Prisma. `createdAt` can be set to
 * control list ordering. Cascade deletes (Portfolio -> Scenario) mean
 * `cleanupTestData` needs no extra step for these rows.
 */
export async function createTestScenario(
  portfolioId: string,
  overrides: {
    name?: string;
    status?: "DRAFT" | "SAVED" | "ARCHIVED";
    changes?: { assetId: string; percentChange: number }[];
    createdAt?: Date;
  } = {},
): Promise<{ id: string }> {
  const row = await prisma.scenario.create({
    data: {
      portfolioId,
      name: overrides.name ?? "Integration test scenario",
      status: overrides.status ?? "DRAFT",
      changes: overrides.changes ?? [],
      ...(overrides.createdAt !== undefined ? { createdAt: overrides.createdAt } : {}),
    },
  });
  return { id: row.id };
}

/**
 * Deletes everything created by the helpers above, for the given user
 * and asset ids. Cascades through portfolios/transactions/positions via
 * Prisma's referential actions where configured; where it is not,
 * deletes explicitly in dependency order (children before parents).
 */
export async function cleanupTestData(params: {
  userIds?: string[];
  assetIds?: string[];
}): Promise<void> {
  const { userIds = [], assetIds = [] } = params;

  if (userIds.length > 0) {
    const portfolios = await prisma.portfolio.findMany({
      where: { userId: { in: userIds } },
      select: { id: true },
    });
    const portfolioIds = portfolios.map((p) => p.id);

    if (portfolioIds.length > 0) {
      await prisma.transaction.deleteMany({ where: { portfolioId: { in: portfolioIds } } });
      await prisma.position.deleteMany({ where: { portfolioId: { in: portfolioIds } } });
      await prisma.portfolio.deleteMany({ where: { id: { in: portfolioIds } } });
    }

    await prisma.credential.deleteMany({ where: { userId: { in: userIds } } });
    await prisma.user.deleteMany({ where: { id: { in: userIds } } });
  }

  if (assetIds.length > 0) {
    await prisma.asset.deleteMany({ where: { id: { in: assetIds } } });
  }
}
