import { afterAll, beforeAll, describe, expect, it } from "vitest";
import request from "supertest";
import { prisma } from "@trading/database";
import { createApp } from "../app.js";
import { body, type DataEnvelope, type ErrorEnvelope } from "../test-utils/api-client.js";
import { tokenFor } from "../test-utils/auth.js";
import { cleanupTestData, createTestNotification, createTestUser } from "../test-utils/fixtures.js";

interface NotificationDto {
  id: string;
  userId: string;
  readAt: string | null;
}

/**
 * Integration tests for notifications.
 * Source: FR-051/052, 07-api-spec.md §28, 09-security-spec.md §14-15.
 *
 * Notifications have no creation endpoint (they are generated by system
 * events), so tests seed them through the createTestNotification fixture.
 * Each test seeds its own data and asserts by id, so tests stay
 * independent of one another.
 */
describe("notifications", () => {
  const app = createApp();
  const userIds: string[] = [];

  let ownerId: string;
  let ownerToken: string;
  let otherId: string;
  let otherToken: string;

  beforeAll(async () => {
    const owner = await createTestUser();
    const other = await createTestUser();
    userIds.push(owner.user.id, other.user.id);

    ownerId = owner.user.id;
    otherId = other.user.id;
    ownerToken = tokenFor(ownerId);
    otherToken = tokenFor(otherId);
  });

  afterAll(async () => {
    await cleanupTestData({ userIds });
  });

  /** Reads a notification's readAt straight from the DB, bypassing the API. */
  async function readAtInDb(id: string): Promise<Date | null> {
    const row = await prisma.notification.findUniqueOrThrow({ where: { id } });
    return row.readAt;
  }

  it.each([
    ["get", "/api/v1/notifications"],
    ["post", "/api/v1/notifications/read-all"],
    ["post", "/api/v1/notifications/some-notification-id/read"],
  ] as const)("rejects unauthenticated %s %s with 401", async (method, path) => {
    const response = await request(app)[method](path);

    expect(response.status).toBe(401);
    expect(body<ErrorEnvelope>(response).error.code).toBe("UNAUTHORIZED");
  });

  it("only lists the caller's own notifications", async () => {
    const mine = await createTestNotification(ownerId);
    const theirs = await createTestNotification(otherId);

    const response = await request(app)
      .get("/api/v1/notifications")
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(response.status).toBe(200);
    const { data } = body<DataEnvelope<NotificationDto[]>>(response);
    expect(data.some((n) => n.id === mine.id)).toBe(true);
    expect(data.some((n) => n.id === theirs.id)).toBe(false);
  });

  it("filters to unread notifications with unreadOnly=true", async () => {
    const unread = await createTestNotification(ownerId);
    const read = await createTestNotification(ownerId, { read: true });

    const response = await request(app)
      .get("/api/v1/notifications?unreadOnly=true")
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(response.status).toBe(200);
    const { data } = body<DataEnvelope<NotificationDto[]>>(response);
    expect(data.some((n) => n.id === unread.id)).toBe(true);
    expect(data.some((n) => n.id === read.id)).toBe(false);
  });

  it("includes read notifications when unreadOnly is omitted", async () => {
    const read = await createTestNotification(ownerId, { read: true });

    const response = await request(app)
      .get("/api/v1/notifications")
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(body<DataEnvelope<NotificationDto[]>>(response).data.some((n) => n.id === read.id)).toBe(
      true,
    );
  });

  it("rejects an invalid unreadOnly value (400)", async () => {
    const response = await request(app)
      .get("/api/v1/notifications?unreadOnly=maybe")
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(response.status).toBe(400);
    expect(body<ErrorEnvelope>(response).error.code).toBe("VALIDATION_ERROR");
  });

  it("marks a notification as read", async () => {
    const notification = await createTestNotification(ownerId);

    const response = await request(app)
      .post(`/api/v1/notifications/${notification.id}/read`)
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(response.status).toBe(200);
    expect(body<DataEnvelope<NotificationDto>>(response).data.readAt).not.toBeNull();
    expect(await readAtInDb(notification.id)).not.toBeNull();
  });

  it("cannot mark another user's notification as read (404, left unread)", async () => {
    const notification = await createTestNotification(ownerId);

    const response = await request(app)
      .post(`/api/v1/notifications/${notification.id}/read`)
      .set("Authorization", `Bearer ${otherToken}`);

    expect(response.status).toBe(404);
    expect(body<ErrorEnvelope>(response).error.code).toBe("NOT_FOUND");
    expect(await readAtInDb(notification.id)).toBeNull();
  });

  it("returns 404 when marking a nonexistent notification as read", async () => {
    const response = await request(app)
      .post("/api/v1/notifications/notification-that-does-not-exist/read")
      .set("Authorization", `Bearer ${ownerToken}`);

    expect(response.status).toBe(404);
  });

  it("marks all of the caller's notifications as read without touching other users'", async () => {
    // Dedicated users so "all unread" is exactly the notifications seeded here.
    const reader = await createTestUser();
    const bystander = await createTestUser();
    userIds.push(reader.user.id, bystander.user.id);

    const readerFirst = await createTestNotification(reader.user.id);
    const readerSecond = await createTestNotification(reader.user.id);
    const bystanderOwn = await createTestNotification(bystander.user.id);

    const response = await request(app)
      .post("/api/v1/notifications/read-all")
      .set("Authorization", `Bearer ${tokenFor(reader.user.id)}`);

    expect(response.status).toBe(204);
    expect(await readAtInDb(readerFirst.id)).not.toBeNull();
    expect(await readAtInDb(readerSecond.id)).not.toBeNull();
    expect(await readAtInDb(bystanderOwn.id)).toBeNull();
  });
});
